# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_cosmo_wrappers", use_symbols = TRUE, package_name = "cosmo")

#' @usage NULL
#' @useDynLib cosmo, .registration = TRUE
NULL

#' Comoving distance.
#' @export
comoving_distance <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distance, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving distance.
#' @export
comoving_distances <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distances, redshift_array, omega_m, omega_k, omega_l, h0)

#' Comoving Volume.
#' @export
comoving_volume <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_volume, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving Volumes
#' @export
comoving_volumes <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_volumes, redshifts, omega_m, omega_k, omega_l, h0)

#' Comoving transverse distance.
#' @export
comoving_trans_distance <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_trans_distance, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving transverse distances for an array
#' @export
comoving_transverse_distances <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_transverse_distances, redshifts, omega_m, omega_k, omega_l, h0)

#' Distance modulus.
#' @export
dist_mod <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__dist_mod, redshift, omega_m, omega_k, omega_l, h0)

#' Distance moduli
#' @export
dist_mods <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__dist_mods, redshifts, omega_m, omega_k, omega_l, h0)


# nolint end
