# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_cosmo_wrappers", use_symbols = TRUE, package_name = "cosmo")

#' @usage NULL
#' @useDynLib cosmo, .registration = TRUE
NULL

#' Comoving distance.
#' @export
comoving_distance <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distance, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving distance.
#' @export
comoving_distances <- function(redshift_array, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_distances, redshift_array, omega_m, omega_k, omega_l, h0)

#' Comoving Volume.
#' @export
comoving_volume <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_volume, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving Volumes
#' @export
comoving_volumes <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_volumes, redshifts, omega_m, omega_k, omega_l, h0)

#' Comoving transverse distance.
#' @export
comoving_trans_distance <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_trans_distance, redshift, omega_m, omega_k, omega_l, h0)

#' Comoving transverse distances for an array
#' @export
comoving_transverse_distances <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__comoving_transverse_distances, redshifts, omega_m, omega_k, omega_l, h0)

#' Distance modulus.
#' @export
dist_mod <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__dist_mod, redshift, omega_m, omega_k, omega_l, h0)

#' Distance moduli
#' @export
dist_mods <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__dist_mods, redshifts, omega_m, omega_k, omega_l, h0)

#' look back time
#' @export
look_back_time <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__look_back_time, redshift, omega_m, omega_k, omega_l, h0)

#' Universe age at z=0
#' @export
universe_age_now <- function(omega_m, omega_k, omega_l, h0) .Call(wrap__universe_age_now, omega_m, omega_k, omega_l, h0)

#' Unviverse age at a particular redshift in Gyr
#' @export
universe_age <- function(redshift, omega_m, omega_k, omega_l, h0) .Call(wrap__universe_age, redshift, omega_m, omega_k, omega_l, h0)

#' Universe ages at multiple redshifts
#' @export
universe_ages <- function(redshifts, omega_m, omega_k, omega_l, h0) .Call(wrap__universe_ages, redshifts, omega_m, omega_k, omega_l, h0)

#' age in Gyr at some given z
#' @export
inverse_age <- function(age, omega_m, omega_k, omega_l, h0) .Call(wrap__inverse_age, age, omega_m, omega_k, omega_l, h0)

#' age in Gyr at given z values
#' @export
inverse_ages <- function(ages, omega_m, omega_k, omega_l, h0) .Call(wrap__inverse_ages, ages, omega_m, omega_k, omega_l, h0)


# nolint end
